# --- !Ups

create table "programs" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar,
  "isPublic" boolean NOT NULL default false,
  "userId" bigint NOT NULL,
  FOREIGN KEY ("userId") REFERENCES users("id")
);

# --- !Downs

drop table "programs" if exists;