# --- !Ups

create table "workouts" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar,
  "programId" bigint NOT NULL,
  FOREIGN KEY ("programId") REFERENCES programs("id")
);

# --- !Downs

drop table "workouts" if exists;