# --- !Ups

create table "exercises" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "description" varchar,
  "resourceUrl" varchar,
  "workoutId" bigint NOT NULL,
  FOREIGN KEY ("workoutId") REFERENCES workouts("id")
);

# --- !Downs

drop table "exercises" if exists;