# --- !Ups

create table "enrollments" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "userId" bigint NOT NULL,
  "programId" bigint NOT NULL,
  "startDate" timestamp NOT NULL,
  FOREIGN KEY ("userId") REFERENCES users("id"),
  FOREIGN KEY ("programId") REFERENCES workouts("id"),
  UNIQUE ("userId", "programId")
);

# --- !Downs

drop table "enrollments" if exists;
