# --- !Ups

create table "weights" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "userId" bigint NOT NULL,
  "value" decimal NOT NULL,
  "createdAt" timestamp NOT NULL,
  FOREIGN KEY ("userId") REFERENCES users("id")
);

# --- !Downs

drop table "trackers" if exists;
